"""Add reminder_time to Task

Revision ID: edfc2795a9aa
Revises: f5e2651fac22
Create Date: 2025-04-05 22:12:48.695217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfc2795a9aa'
down_revision = 'f5e2651fac22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('reminder_time')

    # ### end Alembic commands ###
